# Generated by Django 4.1.5 on 2023-01-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
