# Generated by Django 4.1.5 on 2023-01-15 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_payment_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='amount_subtotal',
        ),
    ]
