# Generated by Django 3.2.16 on 2023-01-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planId', models.CharField(max_length=20)),
                ('planName', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
