# Generated by Django 4.1.5 on 2023-01-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_rename_amount_payment_amount_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='customer_stripe_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
