# Generated by Django 3.2.16 on 2023-01-09 07:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=220)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('address', models.TextField(max_length=300)),
                ('password', models.CharField(max_length=15)),
                ('confirm_password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70, verbose_name='Product Name')),
                ('description', models.TextField(max_length=800, verbose_name='Description')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100000)], verbose_name='Price')),
            ],
        ),
        migrations.AlterField(
            model_name='plan',
            name='planId',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='planName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
