# Generated by Django 4.1.5 on 2023-01-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_customuser_customer_stripe_id_customuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount_subtotal',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
