# Generated by Django 3.2.13 on 2023-01-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_alter_payment_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
