# Generated by Django 3.2.16 on 2023-01-10 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
    ]
