# Generated by Django 3.2.16 on 2023-01-10 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_remove_payment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='product_id',
        ),
    ]
