# Generated by Django 3.2.16 on 2023-01-10 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='pro_name',
            new_name='product_name',
        ),
    ]
